### ISSUE TITLE
no result for SpecHLA_single

### ISSUE THREAD

**Issue by hmyh1202** [deepomicslab/SpecHLA#1]
I use the SpecHLA_single (Pacbio CCS reads) to do HLA type,  but no result ouput . If the coverage of data was two slow ?

**Comment by wshuai294** [comment]
Hello,

Up to now, SpecHLA does not support only use third-generation data. The NGS data is necessary for typing. Then other data can be used to improve the NGS-based results.

Thanks for your usage.
Shuai

**Comment by hmyh1202** [comment]
Hi, shuai:
 I got this error: 
processing reads mapped to chrom "HLA_A"
 run SpecHap ...
input_rephase_para:200  1
Traceback (most recent call last):
  File "single_tgs.py", line 1182, in <module>
    os.system(str(reph))
  File "single_tgs.py", line 433, in newphase
    phased_locus=seq[he]
IndexError: index 0 is out of bounds for axis 0 with size 0

empty for $HLA_A_break_points_spechap.txt HLA_A_break_points_phased.txt
$cat HLA_A_break_points_spechap.txt
#gene   locus   00      01      10      11      points_num      next_locus

next, I will use high coverage PacBio CCS data and NGS data for test.

**Comment by hmyh1202** [comment]
Or  do you have any tools for third-generation data only HLA typing.  Thanks.

**Comment by wshuai294** [comment]
Hi,

As far as I am concerned, there is no tool just use PacBio CCS data only. I know a paper used PacBio HiFi data, but they have not provided the code.

Please let me know if you face any problems running SpecHLA based on NGS and TGS data.

**Comment by hmyh1202** [comment]
As I know HLA-LA support PacBio CCS data only.

My problems is single_tgs.py reported erro when running SpecHLA, as you mentioned it can not use CCS data only.

And I will add NGS data to do hla typing, and what`s the title of the paper which have had do typing use PacBio HiFi data ?

Thank you !

**Comment by wshuai294** [comment]
Hello,

The paper named "Chin, Chen-Shan, et al. "A diploid assembly-based benchmark for variants in the major histocompatibility complex." Nature communications 11.1 (2020): 1-9." uses PacBio HiFi data to assemble the whole MHC region.

Thank you for your information, we will solve the bug using TGS data only, and compare the performance to HLA-LA.

Best,
Shuai

**Comment by hmyh1202** [comment]
Thank you, I am looking forward to your new work. 



Good Luck!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepomicslab/SpecHLA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 下午2:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [deepomicslab/SpecHLA] no result for SpecHLA_single (Issue #1)





 
Hello,
 
The paper named "Chin, Chen-Shan, et al. "A diploid assembly-based benchmark for variants in the major histocompatibility complex." Nature communications 11.1 (2020): 1-9." uses PacBio HiFi data to assemble the whole MHC region.
 
Thank you for your information, we will solve the bug using TGS data only, and compare the performance to HLA-LA.
 
Best,
 Shuai
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wshuai294** [comment]
Hello,

I have revised the TGS-only mode of SpecHLA, and now it works. To use this mode, Please remember to install Longshot 0.4.1 and add it to the system path. 

Please let me know if there are other problems.

Sincerely,
WANG Shuai

**Comment by hmyh1202** [comment]
Thank You ！

**Comment by hmyh1202** [comment]
Hello：

 Do you finished your TGS mode only HLA typing ?
 I have had noticed that you updated some script for HLA assemble.

Thank you!

**Comment by hmyh1202** [comment]
There is no pg_run.py in your git.

**Comment by wshuai294** [comment]
Hello,

Apologies for the delayed response. I'm glad to inform you that we have made significant improvements to the software. The latest version now offers a more streamlined installation process using Conda. To perform HLA typing exclusively with long reads, we recommend utilizing the script/long_read_typing.py. This script is specifically designed to handle long reads and provide accurate HLA typing results.

Thank you for your patience, and please don't hesitate to reach out if you have any further questions or need assistance.

Best regards.
