### ISSUE TITLE
Errors when running SpecHLA.sh 

### ISSUE THREAD

**Issue by bsb2014** [deepomicslab/SpecHLA#12]
Hi there, I got an error below (SpecHLA v1.0.2). Could you please give me some suggestions? Thanks

Attention: please ensure the platform can run gzip -l automatically, otherwise, it may not continue.
less: /home/src/SpecHLA/script/whole/../../spechla_env/lib/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by less)
BAM and VCF are ready.
Mean depth {'HLA_A': 30, 'HLA_B': 29, 'HLA_C': 29, 'HLA_DPA1': 37, 'HLA_DPB1': 48, 'HLA_DQA1': 29, 'HLA_DQB1': 30, 'HLA_DRB1': 29}
Minimum Minor Allele Frequency is 0.05.
Traceback (most recent call last):
  File "/home/src/SpecHLA/script/whole/../phase_variants.py", line 1866, in <module>
    snp_list,beta_set,snp_index_dict = read_vcf(vcffile,outdir,snp_dp,bamfile,indel_len,gene,\
  File "/home/src/SpecHLA/script/whole/../phase_variants.py", line 132, in read_vcf
    in_vcf = VariantFile(vcffile) # convert vcf to double-allele vcf
  File "pysam/libcbcf.pyx", line 4054, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4284, in pysam.libcbcf.VariantFile.open
ValueError: invalid file `b'./bam3_hla/test123/test123.realign.filter.vcf'` (mode=`b'r'`) - is it VCF/BCF format?

The test123.realign.filter.vcf does not have any header and the first line is 

HLA_A   1146    .       C       T       224.05  PASS    AB=0.846154;ABP=16.5402;AC=2;AF=0.666667;AN=3;AO=11;CIGAR=1X;DP=13;DPB=13;DPRA=0;EPP=7.94546;EPPR=7.35324;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=1.89309;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=330;QR=60;RO=2;RPL=2;RPP=12.6832;RPPR=7.35324;RPR=9;RUN=1;SAF=8;SAP=7.94546;SAR=3;SRF=2;SRP=7.35324;SRR=0;TYPE=snp      GT:DP:AD:RO:QR:AO:QA    0/1/1:13:2,11:2:60:11:330

**Comment by wshuai294** [comment]
Hello,
It seems that the SpecHLA failed to run the Linux command `zless` in your platform due to the lack of some dependencies. Please edit the environment so that you can run  `zless` on your platform. Please let me know if this works.

**Comment by bsb2014** [comment]
NCURSES was installed.
 
ncurses                   6.4                  h59595ed_2    conda-forge

and zeless seems no problem.

(base) xxxx@srv3:~/src$  zless
Missing filename ("less --help" for help)

**Comment by bsb2014** [comment]
By the way, do I need to run specHLA inside the conda environment?

**Comment by bsb2014** [comment]
I found that the installation was not complete due to CMake problem.

**Comment by wshuai294** [comment]
Yes, specHLA should be run inside the conda environment.
