### ISSUE TITLE
Install probelm

### ISSUE THREAD

**Issue by bsb2014** [deepomicslab/SpecHLA#13]
Hi there, I got an error during the installation as below

/home/src/SpecHLA/bin/SpecHap/hic_util.h:33:43:   required from here /usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to ‘std::pair<const unsigned int, HiCLinker>::pair(unsigned int&, Fragment&)’ 

Could you please give me some suggestions? Thanks

**Comment by wshuai294** [comment]
Hello, this error can be solved by updating the GCC version. Please see https://github.com/deepomicslab/SpecHap/issues/3
