### ISSUE TITLE
Novel alleles

### ISSUE THREAD

**Issue by bsb2014** [deepomicslab/SpecHLA#15]
if SpecHLA finds novel HLA alleles, will the novel alleles be labeled by "novel" in hla.result.txt file? Thanks

For example,  assuming that HLA_A_2 is a novel HLA allele here
# version: IPD-IMGT/HLA 3.38.0
Sample  HLA_A_1 HLA_A_2
test      A*23:01:01:01  novel

**Comment by wshuai294** [comment]
Hello. SpecHLA will not label `novel` alleles. However, we report the mapping quality in `hla.result.details.txt`. A low mapping quality indicates a novel allele or the low quality of the reconstructed sequence. Users can examine the reconstructed sequence to determine whether a sequence with low mapping quality is novel.

**Comment by bsb2014** [comment]
If there is no N in a reconstructed sequence with low mapping quality, can we say it is a novel allele?

**Comment by wshuai294** [comment]
Yeah, it seems like a novel allele, but it also might be caused by a phasing error. For a gene, if one allele has a high mapping quality and another has a low mapping quality, it may indicate the phasing process is correct and more likely indicates a novel allele.

**Comment by bsb2014** [comment]
That makes sense, thanks.
