### ISSUE TITLE
HLA typing with long-read data 

### ISSUE THREAD

**Issue by vegetableyu** [deepomicslab/SpecHLA#17]
Hello，
I looked at the documentation and I was wondering when performing full-resolution HLA typing with paired-end reads and Nanopore reads or with Nanopore data alone, do I still use the script/ExtractHLAread.sh to extract HLA-related reads from long-read data?
Thanks for SpecHLA and for your time.

**Comment by wshuai294** [comment]
Hi,
It is highly recommended to extract HLA-related reads from long-read data prior to HLA typing to improve efficiency. Without this step, the process can become slow. Similar to short reads, long reads can be aligned to the hg19/38 reference using Minimap2. Subsequently, the script/ExtractHLAread.sh can be executed with the generated BAM file to extract the HLA-related reads.

Best,
Shuai

**Comment by vegetableyu** [comment]
Thanks so much for response.
I have another question: how do you evaluate the typing accuracy since the diploid sequences are not phased? 
If for a locus the gold standard is homozygous AA, the typing result is AB, or vice versa, the gold standard is heterozygous AB, the predicted result is AA, is the typing accuracy for this locus 50%?
