### ISSUE TITLE
ExtractHLAread.sh syntax errors.

### ISSUE THREAD

**Issue by Kelly-ST-HRI** [deepomicslab/SpecHLA#20]
IF/ELSE syntax is not compatible with Bash on CentOS 7.

```
bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

bash script/ExtractHLAread.sh -s NA12878 -b SRE3-230623_gencode.sorted.bam -r hg38 -o /home/user/outs
mkdir: missing operand
Try 'mkdir --help' for more information.
script/ExtractHLAread.sh: line 68: [: ==: unary operator expected
script/ExtractHLAread.sh: line 100: [: ==: unary operator expected
>>>>>>>>>>>>>> indexing extracted bam
[E::hts_open_format] fail to open file '/NA12878.tmp.extract.bam'
samtools index: failed to open "/NA12878.tmp.extract.bam": No such file or directory
>>>>>>>>>>>>>> bamUtil fastq extraction
$bamUtil fastq extraction Failed!
```

Resolves here: https://stackoverflow.com/questions/13617843/unary-operator-expected-error-in-bash-if-condition
https://stackoverflow.com/a/13618376

**Comment by Kelly-ST-HRI** [comment]
I also discovered that order of arguments is important to pass them as arguments: -s -r and -o must occur before -b or they will not be defined.

**Comment by wshuai294** [comment]
It is strange that the order of arguments makes a difference. Have you added any additional comments in the scripts?

**Comment by Kelly-ST-HRI** [comment]
> Have you added any additional comments in the scripts?

No, I've only added echo statements to test to input arguments were parsed correctly. I noticed the "case" input as a combination of tab or space separated lines so it is possible there is a bug in this section.

**Comment by wshuai294** [comment]
I have run 
```
bash ExtractHLAread.sh -b    test.bam -s test -o out     -r hg38
```
and I found the values are defined according to the log
```
Accepted parameters:
-s  test
-b  test.bam
-r  hg38
-o  out
```
Maybe it is caused by the bash version. My bash is 
```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
