### ISSUE TITLE
MICA and MICB

### ISSUE THREAD

**Issue by SQ-Gao** [deepomicslab/SpecHLA#22]
Hello, 
  Can the current software type MICA and MICB genes?

**Comment by wshuai294** [comment]
Hi, currently, SpecHLA does not support these two genes.

**Comment by SQ-Gao** [comment]
Thank you for your reply. Although these two genotypes cannot be typed, I have to say that Spechla is really a good software. ---- Replied Message ----FromWANG ***@***.***>Date01/30/2024 20:48 ***@***.***> CcSiqi ***@***.***>***@***.***>SubjectRe: [deepomicslab/SpecHLA] MICA and MICB (Issue #22)
Hi, currently, SpecHLA does not support these two genes.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/deepomicslab/SpecHLA/issues/22#issuecomment-1916773997",
"url": "https://github.com/deepomicslab/SpecHLA/issues/22#issuecomment-1916773997",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wshuai294** [comment]
Thank you so much. Your appreciation means a great deal to us.
