### ISSUE TITLE
Performace among Novoalign V4, V3 and Bowtie2 in read-binning step

### ISSUE THREAD

**Issue by LongpanUPC** [deepomicslab/SpecHLA#24]
Hi,
   Since it takes time to request Novoalign V4 or money (I requested the license one week ago, but no reply), have you test Novoalign V3 which doesn't need license for the use of research. What's the performance among V4, V3 and Bowtie2? A naive question.

thank you!
Long

**Comment by wshuai294** [comment]
hi,
We have compared the Novoalign V4 with Bowtie2, the result can be found in the supplementary of the [https://pubmed.ncbi.nlm.nih.gov/37714157/](paper). Novoalign V4 performed better. We have not tested Novoalign V3 yet. When I apply license of Novoalign V4, they always reply quickly. Writing the reason in more detail might be helpful.
best,
shuai

**Comment by LongpanUPC** [comment]
Thank you!
  I would like to try again!
Long
