### ISSUE TITLE
HLA typing only based on long-read RNA-seq data?

### ISSUE THREAD

**Issue by yuzhuxuyang** [deepomicslab/SpecHLA#25]
Hi, according to the paper, it says it support RNA-seq data and long-read sequencing data. I am wondering whether it can do HLA typing only based on long-read RNA-seq data (Oxford Nanopore data)?

**Comment by wshuai294** [comment]
Hi,

We have not tested SpecHLA on long-read RNA-seq data. But I think it could work. SpecHLA will mask the region with no reads covered, and then perform typing. Please download the latest commit and run `python long_read_typing.py -k 5 -g 1`, it will afford g-group level results. However, notably, if there is no read covering between exons, it may introduce the switch error.

best,
shuai

**Comment by yuzhuxuyang** [comment]
Hi Shuai, thanks a lot for the clarification!
