### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [deepomicslab/SpecHLA#26]
Would it be possible to add an option to specify the HLA database folder to use, rather than using the hardcoded 'db' option?

**Comment by wshuai294** [comment]
Hi, we can certainly add an option. The database (db) is a customized database created by SpecHLA. Could you please elaborate on the utility of this option or specify the scenarios where it would be applicable? Thanks.

**Comment by Redmar-van-den-Berg** [comment]
When I'm creating a pipeline, I like to have a small test dataset (of both samples and reference files) that I can quickly run to test that the pipeline is working (ideally, it should run in a few seconds). So my use case for this request would be to shrink the database down to only include the alleles that I know are present in my test samples, and then use the small database to test the pipeline I'm working on.

**Comment by wshuai294** [comment]
Hi, the database contains complex information, which makes it difficult to shrink. We do not recommend modifying it. However, even with the original database, SpecHLA can process the provided example data (exon) within a few minutes. If your test data consists of reads from a single gene, it will be even faster. Therefore, we believe the test time should be acceptable with the original database. Thanks.

**Comment by Redmar-van-den-Berg** [comment]
I understand, but I still think it would be nice to not have things like the database location or the conda environment hard coded. Hard coded values make it much more difficult to use the tool and integrate it in other systems, for example conda or biocontainers.

**Comment by wshuai294** [comment]
Agreed, we will add this option as suggested soon. Thanks.

**Comment by Redmar-van-den-Berg** [comment]
@wshuai294 I'm happy to help out with this, would you like me to create a pull request for this functionality?
