### ISSUE TITLE
Publication for SpecHLA

### ISSUE THREAD

**Issue by NTNguyen13** [deepomicslab/SpecHLA#3]
HI, I come across your repository. Could you please provide your publication related to this HLA typing software?

**Comment by wshuai294** [comment]
Hello, 

Thank you for your attention. Our manuscript is still under preparation, and we will send it to you once it has been finished.

**Comment by NTNguyen13** [comment]
Thanks, I am looking forward to the full publication

**Comment by wshuai294** [comment]
Hello,

I hope this message finds you well. I'm excited to share that our manuscript is now available online. You can access it by visiting the following link: [Manuscript Link](https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(23)00240-0).
