### ISSUE TITLE
what's the meanning of  "interval_dict" in long_read_typing.py ? 

### ISSUE THREAD

**Issue by lidd77** [deepomicslab/SpecHLA#30]
Hello , professor,  
         For  "A":"HLA_A:1000-4503"  from the below code line ,    what's the meaning   for  these two number  "1000" and "4503" ?  
         and how to get these  coordinate number  values ,like  "C:1000-5304", "DPA1:1000-10775"   ? 
'''      
interval_dict = {"A":"HLA_A:1000-4503", "B":"HLA_B:1000-5081","C": "HLA_C:1000-5304","DPA1":"HLA_DPA1:1000-10775",\
       "DPB1":"HLA_DPB1:1000-12468","DQA1":"HLA_DQA1:1000-7492","DQB1":"HLA_DQB1:1000-8480","DRB1":"HLA_DRB1:1000-12229" }
'''

Expecting your reply ! 

thank you .

**Comment by wshuai294** [comment]
Hello, because we added upstream and downstream extended 1000bp sequences to the reference allele. So the interval like  "C:1000-5304" represents the actual gene sequence intervals.

**Comment by lidd77** [comment]
> Hello, because we added upstream and downstream extended 1000bp sequences to the reference allele. So the interval like "C:1000-5304" represents the actual gene sequence intervals.

sorry ,  could you give us a script to show us how to get the  interval , for example , how to get the interval for HLA-A ? 
I know HLA-A 's GRCH38 position is  chr6:29,941,260-29,949,572,  so how to get the interval  ?  
I want to know exactly how to set the interval so that I can  understand specHLA deeply and  modify  and test this interval  effect. 

Expecting your reply !

**Comment by wshuai294** [comment]
Hello. For example, we extract the upstream sequence of chr6:29,940,260-29,941,260 (left seq), and the downstream sequence of chr6:29,949,572-29,949,572 (right seq). After that, we combine these two sequences and our reference allele (left seq + allele + right seq). In this case, the edited ref's length is 5503. And the actual HLA-A sequence is in HLA_A:1000-4503".

**Comment by lidd77** [comment]
> Hello. For example, we extract the upstream sequence of chr6:29,940,260-29,941,260 (left seq), and the downstream sequence of **chr6:29,949,572-29,949,572** (right seq). After that, we combine these two sequences and our reference allele (left seq + allele + right seq). In this case, the edited ref's length is 5503. And the actual HLA-A sequence is in HLA_A:1000-4503".

it is typo error ?  for downstream sequence is  chr6:29,949,572-(29,949,572+4503 ) ?

**Comment by wshuai294** [comment]
Our reference allele is different from that in GRCH38.

**Comment by wshuai294** [comment]
Please find the reference allele in the supplementary table of the manuscript.
