### ISSUE TITLE
how to get  hla_gen.format.filter.extend.DRB.no26789.fasta ?

### ISSUE THREAD

**Issue by lidd77** [deepomicslab/SpecHLA#31]
Hello,  
      could you tell us how to get this ref file , hla_gen.format.filter.extend.DRB.no26789.fasta ?
       I checked this fasta , for example , it is only 2-field fasta sequence . so how to get 2-filed allele sequence from IMGT ?
I find IMGT is full resolution sequence database ( 4-field).
      Expecting your repley !

thank you !

**Comment by wshuai294** [comment]
Hi, to reduce computational resources, we only keep one allele at the 2-field resolution in the read binning step.

**Comment by lidd77** [comment]
> Hi, to reduce computational resources, we only keep one allele at the 2-field resolution in the read binning step.

thank you for your reply ! could you send me some scripts to build this  fasta reference ?

**Comment by wshuai294** [comment]
The script to generate the reference is not kept. You can just retain one allele for each group of alleles with the same two-field type. Also, you can simply keep all the alleles.

**Comment by lidd77** [comment]
> The script to generate the reference is not kept. You can just retain one allele for each group of alleles with the same two-field type. Also, you can simply keep all the alleles.

Hello,
        I find this file hla_gen.format.filter.extend.DRB.no26789.fasta  don't update its allele list against  IMGT3.39 .
        for example,  
the next list is  in   hla_gen.format.filter.extend.DRB.no26789.fasta .
>DQB1*02:01
>DQB1*02:02
>DQB1*03:01
>DQB1*03:02
>DQB1*03:04
>DQB1*03:05
>DQB1*03:19
>DQB1*04:01
>DQB1*04:02
>DQB1*05:01
>DQB1*05:02
>DQB1*05:03
>DQB1*05:04
>DQB1*06:01
>DQB1*06:02
>DQB1*06:03
>DQB1*06:04
>DQB1*06:07
>DQB1*06:08
>DQB1*06:09
>DQB1*06:10
>DQB1*06:11
>DQB1*06:14
>DQB1*06:20

but I  check  DQB1 in   IMGTHLA-3.39.0-alpha/fasta/DQB1_gen.fasta and find so many alleles not in that file .
for example, these below alleles not in  hla_gen.format.filter.extend.DRB.no26789.fasta.  
>HLA:HLA06518 DQB1*06:44 6373 bp
>HLA:HLA06877 DQB1*06:46 6700 bp
>HLA:HLA07539 DQB1*06:48:01 6561 bp
>HLA:HLA07820 DQB1*06:49 6671 bp
>HLA:HLA09472 DQB1*06:84 7102 bp
>HLA:HLA09733 DQB1*06:90 7103 bp

this situation will cause that specHLA miss some allele typing ? 

Expecting your reply !

@wshuai294

**Comment by wshuai294** [comment]
Please have a look at the manuscript for this part.
