### ISSUE TITLE
Typing long reads

### ISSUE THREAD

**Issue by oumodavid1625** [deepomicslab/SpecHLA#33]
Hello
Help me with long read typing
I tried_
`bash script/ long_read_typing.py -j 5 -n HLAs1 -r HLAs1. fastq -o output_`

**Comment by wshuai294** [comment]
Hello,
Thanks for using SpecHLA. What error did you meet after running this command?

**Comment by oumodavid1625** [comment]
![Uploading 17162820474364126336947125677332.jpg…]()

**Comment by wshuai294** [comment]
I cannot open the screenshot.

**Comment by oumodavid1625** [comment]
`script/long_read_typing.py: line 4: $`\r\nFunction 1: assign long reads to the gene\r\nFunction 2 : typing with only long reads\r\n\r`: command not found
script/long_read_typing.py: line 5: $`\r': command not found`

**Comment by wshuai294** [comment]
Hello，as this is a Python script， you should run it with python3.在 2024年5月21日，17:10，oumodavid1625 ***@***.***> 写道：﻿
script/long_read_typing.py: line 4: $\r\nFunction 1: assign long reads to the gene\r\nFunction 2 : typing with only long reads\r\n\r: command not found script/long_read_typing.py: line 5: $\r': command not found`

**Comment by oumodavid1625** [comment]
Thank you, this one worked

**Comment by wshuai294** [comment]
Good to hear this.
