### ISSUE TITLE
use deep-variants calling too to replace longshot ?

### ISSUE THREAD

**Issue by lidd77** [deepomicslab/SpecHLA#38]
hey, 
   For nanopore sequencing data ,  I find  deepvariant can also do snvs calling , so do you have a plan to use  deepvariant tool   to replace  longshot ?
   or longshot is better than deepvariant based your testing ?

Expecting your reply !

**Comment by wshuai294** [comment]
I have not tested deepvariant yet. But it may also work well.

**Comment by alisamatisse** [comment]
yesss it would be nice to incorporate DeepVaraint, as it seems also to work the best for different kinds of sequencing data!
