### ISSUE TITLE
NGS Whole genome pipeline hang at run.assembly.realign.sh

### ISSUE THREAD

**Issue by NTNguyen13** [deepomicslab/SpecHLA#4]
Hi, I am trying out SpecHLA using example data.
I have installed and indexed the tool according with some modification, because the shared library is missing when using bowtie2 from `bin` directory => I installed bowtie2 by conda, and changed the path in `index.sh`

(the error when using direct bowtie2 `SpecHLA/bin/bowtie2/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory`)

When I used the script: `bash SpecHLA.sh -n test_wgs -1 HG00118_1.filter.fastq.gz -2 HG00118_2.filter.fastq.gz -p Caucasian -o output`
it hanged at `run.assembly.realign.sh`. I checked the log file (test_wgs.local_assem.log), the last 5 lines are:

```
SpecHLA/script/../bin/fermikit/fermi.kit/bfc -1s 1k -k 10 -t 5 output/test_wgs/prefix2.ec.fq.gz 2> output/test_wgs/prefix2.flt.fq.gz.log | gzip -1 > output/test_wgs/prefix2.flt.fq.gz
SpecHLA/script/../bin/fermikit/fermi.kit/ropebwt2 -dNCr output/test_wgs/prefix2.flt.fq.gz > output/test_wgs/prefix2.flt.fmd 2> output/test_wgs/prefix2.flt.fmd.log
SpecHLA/script/../bin/fermikit/fermi.kit/fermi2 assemble -l 40 -m 53 -t 5 output/test_wgs/prefix2.flt.fmd 2> output/test_wgs/prefix2.pre.gz.log | gzip -1 > output/test_wgs/prefix2.pre.gz
SpecHLA/script/../bin/fermikit/fermi.kit/fermi2 simplify -CSo 45 -m 53 -T 40 output/test_wgs/prefix2.pre.gz 2> output/test_wgs/prefix2.mag.gz.log | gzip -1 > output/test_wgs/prefix2.mag.gz
"output/test_wgs/prefix2.mag.gz" may be a binary file.  See it anyway? 
```

the file `output/test_wgs/prefix2.mag.gz` is empty

Could you please help me debug this issue please?

**Comment by wshuai294** [comment]
Hello, is the file `A.R1.fq.gz` empty? If it is empty, please make sure to remove  `:<<!` in `SpecHLA.sh`.  Because the software is still under revision, some codes might be commented in `SpecHLA.sh`.  `run.assembly.realign.sh` will take a while to run, and do not worry about the warning in `test_wgs.local_assem.log`. Could you send me the log information on the screen?

**Comment by wshuai294** [comment]
Hello, we have solved this bug which is caused by the confusion of the Linus orders `less` and `zless`.
