### ISSUE TITLE
Diploid asm

### ISSUE THREAD

**Issue by bsb2014** [deepomicslab/SpecHLA#5]
Can the SpecHLA work with diploid assembly as HLA*ASM? Possibly, long-read option works for that? Thanks!

**Comment by wshuai294** [comment]
Hello, as you said, I think the diploid assembly can be converted to the fastq format like long-read data (generate multiple reads for each assembly), and the long-read option can be used for typing. Also, it might be a good choice to directly align each assembly to the IMGT database using minimap2 for typing annotation.

**Comment by wshuai294** [comment]
Solved in https://github.com/deepomicslab/SpecHLA/issues/14
