### ISSUE TITLE
Possibility to Update and Display IMGT/HLA Database Version in Output

### ISSUE THREAD

**Issue by joaohccampos** [deepomicslab/SpecHLA#7]
Hello!

Congratulations on the effort to produce this tool. Would it be possible to update the IMGT/HLA database to the most recent version, or if the software already does this, could you include the database version used for HLA typing in the output?

Thank you.

**Comment by wshuai294** [comment]
Thank you for providing such valuable advice. We greatly appreciate it. We will be implementing support for IMGT version selection and adding version information to the output in the near future.

**Comment by wshuai294** [comment]
Hello,

Thanks again for the valuable suggestion. As suggested, we added the IMGT version information to the typing results. Also, we allow users to get the most recent IMGT database for annotation. Please see the changes in SpecHLA v1.0.2 or the latest commit.

**Comment by joaohccampos** [comment]
Hello,
Thank you for implementing the suggested changes. I believe these modifications will be of great utility, especially as they ensure that new alleles progressively added to the IMGT database remain accessible to the tool. I'm excited to test out the new features in SpecHLA v1.0.2. Keep up the great work!
Best regards,
