### ISSUE TITLE
multithreading does not work

### ISSUE THREAD

**Issue by Cimorgh-IT** [deepomicslab/SpecHLA#8]
I have followed exactly the steps mentioned for installation and using. Now, I am doing HLA typing on WES data with -u 1 and -j 12. but SpecHLA only uses one core. how can I do it in parallel mode ?

**Comment by wshuai294** [comment]
Hello, Thanks for using it. 

SpecHLA supports multithreading in almost all the steps except for variant calling using Freebayes. Did SpecHLA only use one core in all the steps or in only specific steps? Moreover, how long did SpecHLA take to run your WES data? Which step did you find took the most time? Please give me more detailed information, and I will be happy to help you accelerate the typing process.

**Comment by Cimorgh-IT** [comment]
I noticed that since I did not have bam/cram file, I started from second part. hence It took too long to extract uniq_reads.

**Comment by wshuai294** [comment]
Oh, I see. Mapping untargeted sequencing data onto the database is slow. It is recommended to map the raw data to the hg19/hg38 reference and extract the HLA-related reads first.
