### ISSUE TITLE
Question about ploidy for LOH

### ISSUE THREAD

**Issue by Jwong684** [deepomicslab/SpecHLA#9]
Hi SpecHLA developers,

Your tool has been incredibly easy to set up and use so far. I just wanted a clarification on your cal.hla.copy.pl function.

In your description you had --ploidy as "the ploidy of tumor sample in HLA gene region". What would you put if you detected focal CNV deletions or gains at different HLA regions here?

**Comment by wshuai294** [comment]
Hello,

Thank you for your interest in SpecHLA. Sorry for the misleading description. The ploidy estimation is applicable to the entire tumor sample and is not specific to HLA regions. To infer the ploidy and tumor purity, we recommend utilizing software tools such as Absolute and ASCAT.

**Comment by Jwong684** [comment]
Ah thank you for the clarification!
